# Generated by Django 4.0.3 on 2022-06-01 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carausel',
        ),
    ]
